services:
  minecraft:
    build: ./minecraft
    container_name: minecraft-server
    environment:
      - EULA=${EULA}
      - VERSION=${VERSION}
      - MEMORY=${MEMORY}
      - DIFFICULTY=${DIFFICULTY}      
      - ENABLE_WHITELIST=${ENABLE_WHITELIST}
      - WHITELIST=${WHITELIST}
      - OPS=${OPS}
    ports:
      - "25565:25565"  # Expose Minecraft server port
    volumes:
      - ./data:/data  # Persist Minecraft data
    restart: unless-stopped

  ngrok:
    build: ./ngrok
    container_name: ngrok-connecter
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} #Enter your NGROK_AUTHTOKEN
    network_mode: host  # Use the host network for ngrok
    depends_on: 
      - minecraft
    restart: unless-stopped
